### ISSUE TITLE
reshape instead of view

### ISSUE THREAD

**Issue by kargaranamir** [lushleaf/Network-Pruning-Greedy-Forward-Selection#3]
if i replace the "view(-1)" with "reshape(-1)" the error will be resolved. Does this cause a problem with the code logic?

log:
```
=> Preparing data..
=> Preparing data..
Using SGD...
weight decay  = 4e-05
=> Start pruning...
Pruning mobilenet on imagenet...
Traceback (most recent call last):
  File "./mobile2_prune.py", line 504, in <module>
    net_prune()
  File "./mobile2_prune.py", line 268, in net_prune
    a_para, a_num, global_cur_top1, isalladd = prune_a_layer(m)
  File "./mobile2_prune.py", line 165, in prune_a_layer
    init_loss, init_top1, init_top5 = eval_train(net, eval_train_loader)
  File "./mobile2_prune.py", line 418, in eval_train
    prec1, prec5 = accuracy(outputs.data, targets.data, topk=(1, 5))
  File "/content/lib/utils.py", line 79, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by lushleaf** [comment]
.view(-1) is for older version of pytorch. I've fixed this issue for a newer version pytorch. Thanks very much for pointing out!
